### PR TITLE
Alex Dykas

### PR DESCRIPTION
**Pull request by udykas**

### CODE REVIEW

**Comment by udykas** [comment]
```server.post('/api/actions', (req, res) => {
    const { project_id, description } = req.body;
    if(!project_id || !description){
        errorStatus(400, 'Please provide a project id and description for your action', res);
        return;
    }
    actions        
        .insert({ project_id, description })
        .then(action => {
            res.json({action});
        })
        .catch(err => {
            errorStatus(500, 'There was an error posting your action', res)
        })
})

**Comment by udykas** [comment]
For some reason I cant post a new action. The above comment is my current code. Can't find any errors.

**Comment by etisdew** [comment]
I'd make sure you res.status(200) first but that shouldnt prevent the dispatch. No errors just a ghost of the functionality?

**Comment by udykas** [comment]
It returns my 500 error status

**Pull request closed without merging**
